/**
 * Deterministic seed data.
 *
 * Ids are fixed strings so that re-running the seed never creates duplicates
 * (every row is upserted by id).
 *
 * Designed scenarios:
 * - `order-reactor-module` (80 kg) exceeds every rover capacity -> impossible;
 * - `order-drill-rig` (45 kg) fits only Cargo-02;
 * - `order-geo-samples` (Aitken basin) needs more battery than any rover has;
 * - `order-oxygen-tanks` and `order-antenna-repair` are critical orders.
 *
 * Game Design v2: rovers now start at level 0 on every upgrade, with the
 * battery split into batteryCharge (current) and batteryCapacity (maximum).
 * Urgency values use the new internal scale (normal | urgent | critical).
 */

import type {
  MoonLocation,
  Order,
  OrderStatus,
  Rover,
  RoverStatus,
} from '../src/domain/types'

export const SEED_LOCATIONS: readonly MoonLocation[] = [
  {
    id: 'loc-serenity',
    name: 'Море Ясности',
    x: 120,
    y: 80,
    distance: 18,
    zoneType: 'plain',
    batteryModifier: 1,
    speedModifier: 1,
    riskBonus: 0,
  },
  {
    id: 'loc-tranquility',
    name: 'Море Спокойствия',
    x: 60,
    y: 150,
    distance: 24,
    zoneType: 'plain',
    batteryModifier: 1.05,
    speedModifier: 1,
    riskBonus: 2,
  },
  {
    id: 'loc-copernicus',
    name: 'Кратер Коперник',
    x: 195,
    y: 65,
    distance: 35,
    zoneType: 'crater',
    batteryModifier: 1.3,
    speedModifier: 0.8,
    riskBonus: 8,
  },
  {
    id: 'loc-tycho',
    name: 'Кратер Тихо',
    x: 150,
    y: 205,
    distance: 48,
    zoneType: 'crater',
    batteryModifier: 1.35,
    speedModifier: 0.75,
    riskBonus: 12,
  },
  {
    id: 'loc-shackleton',
    name: 'Кратер Шеклтон',
    x: 240,
    y: 245,
    distance: 72,
    zoneType: 'dark',
    batteryModifier: 1.6,
    speedModifier: 0.6,
    riskBonus: 20,
  },
  {
    id: 'loc-aitken',
    name: 'Бассейн Айткена',
    x: 45,
    y: 255,
    distance: 88,
    zoneType: 'dark',
    batteryModifier: 1.7,
    speedModifier: 0.55,
    riskBonus: 25,
  },
]

const IDLE: RoverStatus = 'idle'

export const SEED_ROVERS: readonly Rover[] = [
  {
    id: 'rover-scout-01',
    name: 'Scout-01',
    batteryCharge: 100,
    batteryCapacity: 100,
    capacity: 20,
    speed: 6,
    efficiency: 1.4,
    capacityLevel: 0,
    speedLevel: 0,
    efficiencyLevel: 0,
    batteryLevel: 0,
    safetyLevel: 0,
    status: IDLE,
  },
  {
    id: 'rover-cargo-02',
    name: 'Cargo-02',
    batteryCharge: 100,
    batteryCapacity: 100,
    capacity: 60,
    speed: 3,
    efficiency: 0.9,
    capacityLevel: 0,
    speedLevel: 0,
    efficiencyLevel: 0,
    batteryLevel: 0,
    safetyLevel: 0,
    status: IDLE,
  },
  {
    id: 'rover-sprint-03',
    name: 'Sprint-03',
    batteryCharge: 100,
    batteryCapacity: 100,
    capacity: 35,
    speed: 9,
    efficiency: 1.1,
    capacityLevel: 0,
    speedLevel: 0,
    efficiencyLevel: 0,
    batteryLevel: 0,
    safetyLevel: 0,
    status: IDLE,
  },
]

const AVAILABLE: OrderStatus = 'available'

export const SEED_ORDERS: readonly Order[] = [
  {
    id: 'order-medkits',
    title: 'Медикаменты для станции',
    description: 'Лёгкий близкий рейс — безопасный старт для любого ровера.',
    locationId: 'loc-serenity',
    weight: 8,
    reward: 320,
    urgency: 'urgent',
    baseRisk: 5,
    deadlineDay: 2,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-spare-parts',
    title: 'Запчасти для ровера',
    description: 'Небольшой груз с запасом времени.',
    locationId: 'loc-tranquility',
    weight: 5,
    reward: 240,
    urgency: 'normal',
    baseRisk: 4,
    deadlineDay: 6,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-solar-panels',
    title: 'Солнечные панели',
    description: 'Средний вес: Scout-01 уже не справится.',
    locationId: 'loc-serenity',
    weight: 25,
    reward: 430,
    urgency: 'normal',
    baseRisk: 6,
    deadlineDay: 5,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-water-tanks',
    title: 'Контейнеры с водой',
    description: 'Тяжёлый груз: требует Sprint-03 или Cargo-02.',
    locationId: 'loc-tranquility',
    weight: 30,
    reward: 520,
    urgency: 'urgent',
    baseRisk: 8,
    deadlineDay: 3,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-antenna-repair',
    title: 'Ремонт антенны связи',
    description: 'Критичный заказ в кратере с коротким дедлайном.',
    locationId: 'loc-copernicus',
    weight: 15,
    reward: 610,
    urgency: 'critical',
    baseRisk: 14,
    deadlineDay: 2,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-drill-rig',
    title: 'Буровая установка',
    description: '45 кг: влезает только в Cargo-02.',
    locationId: 'loc-copernicus',
    weight: 45,
    reward: 900,
    urgency: 'normal',
    baseRisk: 10,
    deadlineDay: 4,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-oxygen-tanks',
    title: 'Кислородные баллоны',
    description: 'Критичный рейс в тёмную зону: высокий риск и большой расход.',
    locationId: 'loc-shackleton',
    weight: 18,
    reward: 780,
    urgency: 'critical',
    baseRisk: 20,
    deadlineDay: 3,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-reactor-module',
    title: 'Реакторный модуль',
    description: '80 кг: невыполнимо — превышает грузоподъёмность всех роверов.',
    locationId: 'loc-tycho',
    weight: 80,
    reward: 1500,
    urgency: 'normal',
    baseRisk: 15,
    deadlineDay: 6,
    isChallenge: false,
    status: AVAILABLE,
  },
  {
    id: 'order-geo-samples',
    title: 'Геологические образцы',
    description:
      'Бассейн Айткена: маршрут недоступен любому роверу из-за батареи.',
    locationId: 'loc-aitken',
    weight: 12,
    reward: 850,
    urgency: 'normal',
    baseRisk: 12,
    deadlineDay: 7,
    isChallenge: false,
    status: AVAILABLE,
  },
]
